"""'123'

Revision ID: 110c357a59b6
Revises: 1729179f197d
Create Date: 2026-09-17 10:19:12.636649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110c357a59b6'
down_revision: Union[str, None] = '1729179f197d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('_name', sa.String(length=100), nullable=False))
    op.drop_column('halls', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('halls', '_name')
    # ### end Alembic commands ###
