"""remove unique constraint from booking.seat_id

Revision ID: 4b1ce3b4e2ce
Revises: 8d6af327bdb6
Create Date: 2026-10-06 14:27:18.701790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b1ce3b4e2ce'
down_revision: Union[str, None] = '8d6af327bdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_seat_id_key', 'booking', type_='unique')
    op.create_index('uq_booking_seat_active', 'booking', ['seat_id'], unique=True, postgresql_where=sa.text("status IN ('reserved', 'sold')"))
    op.drop_column('halls', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('halls', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('uq_booking_seat_active', table_name='booking', postgresql_where=sa.text("status IN ('reserved', 'sold')"))
    op.create_unique_constraint('booking_seat_id_key', 'booking', ['seat_id'])
    # ### end Alembic commands ###
