"""'init'

Revision ID: ef8fd5784018
Revises: 
Create Date: 2026-09-10 10:02:11.936819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8fd5784018'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('free', 'reserved', 'sold', 'unavailable', 'blocked', name='SeatStatusEnum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_id'), 'seat', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reserved', 'sold', 'expired', 'cancelled', 'failed', name='BookingStatusEnum'), nullable=False),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    op.create_index(op.f('ix_booking_idempotency_key'), 'booking', ['idempotency_key'], unique=True)
    op.drop_constraint('booking_seat_id_key', 'booking', type_='unique')
    op.create_index(
        'uq_booking_seat_active',
        'booking',
        ['seat_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('reserved', 'sold')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_booking_seat_active', table_name='booking')
    op.create_unique_constraint('booking_seat_id_key', 'booking', ['seat_id'])
    op.drop_index(op.f('ix_booking_idempotency_key'), table_name='booking')
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_table('users')
    op.drop_index(op.f('ix_seat_id'), table_name='seat')
    op.drop_table('seat')
    # ### end Alembic commands ###
